### PR TITLE
Fixed Quote struct

### PR DESCRIPTION
**Pull request by fabianbaier**
Currently the [Quote struct](https://github.com/goinvest/iexcloud/blob/4516920dbd9cd36dab1692cf7ace90996f3ffcb3/stocks.go#L326-L365) has imo wrong assigned types and fields.

This should fix https://github.com/goinvest/iexcloud/issues/14

### CODE REVIEW

**Comment by matthewrankin** [comment]
I agree with your changes, except I think we want to use `EpochTime` instead of `*EpochTime` for the time related fields in the `Quote` struct. Thoughts?

**Comment by fabianbaier** [comment]
When changing from `*EpochTime` to `EpochTime` I saw that the output was not the desired one, in fact `{}` with no times. When changing to `*EpochTime` the correct times where provided. But correct me if I am wrong but those are my thoughts for now.

Example with `*EpochTime` for `NVDA`:
```
$ go run main.go quote NVDA
## Quote ##
{
  "symbol": "NVDA",
  "companyName": "NVIDIA Corporation",
  "calculationPrice": "close",
  "open": 158,
  "openTime": 1551709800,
  "close": 156.78,
  "closeTime": 1551733200,
  "high": 158.92,
  "low": 0,
  "latestPrice": 156.78,
  "latestSource": "Close",
  "latestTime": "March 4, 2019",
  "latestUpdate": 1551733200,
  "latestVolume": 10238603,
  "iexRealtimePrice": 156.78,
  "iexRealtimeSize": 100,
  "iexLastUpdated": 1551733199,
  "delayedPrice": 156.65,
  "delayedPriceTime": 1551734100,
  "extendedPrice": 156.5,
  "extendedChange": -0.28,
  "extendedChangePercent": -0.00179,
  "extendedPriceTime": 1551743096,
  "previousClose": 156.45,
  "change": 0.33,
  "changePercent": 0.00211,
  "iexMarketPercent": 0.013426245748565503,
  "iexVolume": 137466,
  "avgTotalVolume": 17955841,
  "iexBidPrice": 0,
  "iexBidSize": 0,
  "iexAskPrice": 0,
  "iexAskSize": 0,
  "marketCap": 95008680000,
  "week52High": 292.76,
  "week52Low": 0,
  "ytdChange": 0.15062
}
```

Versus when having it with `EpochTime`:
```
$ go run main.go quote NVDA
## Quote ##
{
  "symbol": "NVDA",
  "companyName": "NVIDIA Corporation",
  "calculationPrice": "close",
  "open": 158,
  "openTime": {},
  "close": 156.78,
  "closeTime": {},
  "high": 158.92,
  "low": 0,
  "latestPrice": 156.78,
  "latestSource": "Close",
  "latestTime": "March 4, 2019",
  "latestUpdate": {},
  "latestVolume": 10238603,
  "iexRealtimePrice": 156.78,
  "iexRealtimeSize": 100,
  "iexLastUpdated": {},
  "delayedPrice": 156.65,
  "delayedPriceTime": {},
  "extendedPrice": 156.5,
  "extendedChange": -0.28,
  "extendedChangePercent": -0.00179,
  "extendedPriceTime": {},
  "previousClose": 156.45,
  "change": 0.33,
  "changePercent": 0.00211,
  "iexMarketPercent": 0.013426245748565503,
  "iexVolume": 137466,
  "avgTotalVolume": 17955841,
  "iexBidPrice": 0,
  "iexBidSize": 0,
  "iexAskPrice": 0,
  "iexAskSize": 0,
  "marketCap": 95008680000,
  "week52High": 292.76,
  "week52Low": 0,
  "ytdChange": 0.15062
}
```

**Comment by Redorb** [comment]
It's a bit of weirdness with using MarshalIndent, I don't think there is a way to make it display nested structs. If you change the quote example code to:
```
var quoteCmd = &cobra.Command{
	Use:   "quote [stock]",
	Short: "Retrieve the quote data for stock symbol",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		stock := args[0]
		cfg, err := domain.ReadConfig(configFileFlag)
		if err != nil {
			log.Fatalf("Error reading config file: %s", err)
		}
		client := iex.NewClient(cfg.Token, cfg.BaseURL)
		quote, err := client.Quote(stock)
		if err != nil {
			log.Fatalf("Error getting quote: %s", err)
		}
		fmt.Println("## Quote ##")
		fmt.Printf("%+v\n", quote)
	},
}
```

Which will result in the following output:
```
iexcloud (master *): go run main.go quote NVDA
## Quote ##
{Symbol:NVDA CompanyName:NVIDIA Corporation CalculationPrice:close Open:158 OpenTime:2019-03-04 06:30:00 -0800 PST Close:156.45 CloseTime:2019-03-04 13:00:00 -0800 PST High:158.92 Low:0 LatestPrice:156.45 LatestSource:Close LatestTime:March 4, 2019 LatestUpdate:2019-03-04 13:00:00 -0800 PST LatestVolume:10238603 IEXRealtimePrice:156.78 IEXRealtimeSize:100 IEXLastUpdated:2019-03-04 12:59:59 -0800 PST DelayedPrice:156.65 DelayedTime: ExtendedPrice:156.5 ExtendedChange:0.05 ExtendedChangePercent:0.00032 ExtendedPriceTime:1551743096062 PreviousClose:154.26 Change:2.19 ChangePercent:0.0142 IEXMarketPercent:0.013426245748565503 IEXVolume:137466 AvgTotalVolume:17955841 IEXBidPrice:0 IEXBidSize:0 IEXAskPrice:0 IEXAskSize:0 MarketCap:94808700000 Week52High:292.76 Week52Low:0 YTDChange:0.16271}
```

Not as pretty, but as you can tell the times are shown correctly. I'm not sure if there is a way to have both the pretty printing and show nested structs without a thirdparty lib.

**Comment by Redorb** [comment]
So I looked into it a bit and I think I made a mistake on implementation. When creating a MarshalJSON() implementation it seems to be recommended that it's done on a non-pointer receiver per this issue (https://github.com/golang/go/issues/7536). The correct implementation of MarshalJSON() should be like so:
```
// MarshalJSON implements the Marshaler interface for EpochTime.
func (e EpochTime) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprint(time.Time(e).Unix())), nil
}
```

This will result in:
```
iexcloud (master *): go run main.go quote NVDA
## Quote ##
{
  "symbol": "NVDA",
  "companyName": "NVIDIA Corporation",
  "calculationPrice": "close",
  "open": 158,
  "openTime": 1551709800,
  "close": 156.45,
  "closeTime": 1551733200,
  "high": 158.92,
  "low": 0,
  "latestPrice": 156.45,
  "latestSource": "Close",
  "latestTime": "March 4, 2019",
  "latestUpdate": 1551733200,
  "latestVolume": 10238603,
  "iexRealtimePrice": 156.78,
  "iexRealtimeSize": 100,
  "iexLastUpdated": 1551733199,
  "delayedPrice": 156.65,
  "delayedTime": "",
  "extendedPrice": 156.5,
  "extendedChange": 0.05,
  "extendedChangePercent": 0.00032,
  "extendedPriceTime": 1551743096062,
  "previousClose": 154.26,
  "change": 2.19,
  "changePercent": 0.0142,
  "iexMarketPercent": 0.013426245748565503,
  "iexVolume": 137466,
  "avgTotalVolume": 17955841,
  "iexBidPrice": 0,
  "iexBidSize": 0,
  "iexAskPrice": 0,
  "iexAskSize": 0,
  "marketCap": 94808700000,
  "week52High": 292.76,
  "week52Low": 0,
  "ytdChange": 0.16271
}
```

I think we'll need to the same thing to the other MarshalJSON implementations. I can do the PR, but it'll be a bit later.

**Comment by fabianbaier** [comment]
Right, but looking at the response, e.g. for `OpenTime` that is e.g. `2019-03-04 06:30:00 -0800 PST` this is not what I would expect from the [API reference](https://iexcloud.io/docs/api/#quote) that states it's a `number`. 

So what I would expect is a `number` like `  "openTime": 1506605400394` (from the example) which is in EpochTime and not a time format  in `RFC 3339` or am I missing something?

**Comment by Redorb** [comment]
If we do reimplement EpochTime MarshalJSON as a non-pointer receiver we would get:
```
## Quote ##
{
  "symbol": "NVDA",
  "companyName": "NVIDIA Corporation",
  "calculationPrice": "close",
  "open": 158,
  "openTime": 1551709800,
  "close": 156.45,
  "closeTime": 1551733200,
  "high": 158.92,
  "low": 0,
  "latestPrice": 156.45,
  "latestSource": "Close",
  "latestTime": "March 4, 2019",
  "latestUpdate": 1551733200,
  "latestVolume": 10238603,
  "iexRealtimePrice": 156.78,
  "iexRealtimeSize": 100,
  "iexLastUpdated": 1551733199,
  "delayedPrice": 156.65,
  "delayedTime": "",
  "extendedPrice": 156.5,
  "extendedChange": 0.05,
  "extendedChangePercent": 0.00032,
  "extendedPriceTime": 1551743096062,
  "previousClose": 154.26,
  "change": 2.19,
  "changePercent": 0.0142,
  "iexMarketPercent": 0.013426245748565503,
  "iexVolume": 137466,
  "avgTotalVolume": 17955841,
  "iexBidPrice": 0,
  "iexBidSize": 0,
  "iexAskPrice": 0,
  "iexAskSize": 0,
  "marketCap": 94808700000,
  "week52High": 292.76,
  "week52Low": 0,
  "ytdChange": 0.16271
}
```
so just:
```
func (e *EpochTime) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprint(time.Time(*e).Unix())), nil
}
```
to
```
func (e EpochTime) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprint(time.Time(e).Unix())), nil
}
```

It's back to the unix timestamp style; but it's at least legible on the output.

**Comment by Redorb** [comment]
I mean that's fair and probably warrants a larger discussion in a separate issue. The 10000 ft view of switching it to a time object is that it makes easier to perform operations on the field.

**Pull request merged**
