### PR TITLE
Merge all changes from master to v2

### PR DESCRIPTION
**Pull request by judearavinda**
We are using the v2 branch. I was wondering if we can update the changes from v2 with all the changes that we did to master.

### CODE REVIEW

**Comment by GrandNewbien** [comment]
I've tested this and it works correctly.

Changes submitted to master should be pulled into v2 if it passes any testing.

**Comment by GrandNewbien** [comment]
@matthewrankin Is there an update on this PR?

**Comment by matthewrankin** [comment]
@GrandNewbien As part of issue #30 the v2 development was moved to master. Is there a reason you can't use master instead of v2?

**Comment by GrandNewbien** [comment]
I believe go throws errors if you have have branches higher than v0. It'll go back to the last tagged v2, which was November I believe.

**Comment by matthewrankin** [comment]
The last tag was [v2.8.0](https://github.com/goinvest/iexcloud/releases/tag/v2.8.0) from five days ago, but I noticed that it accidentally was the same as v2.7.0, which missed the most recent change. I've pushed a new tag, so you should be able to use [v2.9.0](https://github.com/goinvest/iexcloud/releases/tag/v2.9.0).

**Comment by GrandNewbien** [comment]
Ah I see. We've been having package conflicts, but perhaps we'll have to do more reading on how to make master work.

**Comment by judearavinda** [comment]
Closing the PR since we are supposed to pull off the latest tag.

**Pull request closed without merging**
