### PR TITLE
Make all calls context-aware.

### PR DESCRIPTION
**Pull request by DerekDuchesne**
Sponsored-by: BackendBenchmarking (backendb.com)

### CODE REVIEW

**Comment by DerekDuchesne** [comment]
Fixes #22 .

The target branch is master right now because that's the only one I could select. Can you create a v2 branch?

**Comment by someone1** [comment]
It probably makes sense to:

- [ ] Merge #28 into master first (its a non-breaking change)
- [ ] Create a v2 branch from the updated master
- [ ] Rebase this PR on the updated master and point it towards the v2 branch

**Comment by Seklfreak** [comment]
Since we are doing breaking changes, can we consider removing `baseURL string` as an argument for `NewClient`? We can add it back as an option, but I don't think we need to have it there because usually you want to set it to `""`, to use the default value. Not sure if it's best to hijack this branch though, or to create v3? I have not much experience with dealing with Go mod versioning.

**Comment by someone1** [comment]
@Seklfreak - that's a fine idea, moving to a client option makes the most sense. 

@matthewrankin - is this ok with you? If so, @DerekDuchesne can make the quick/easy switch when rebasing and pointing this PR on a v2 branch.

**Comment by matthewrankin** [comment]
Yes. That's fine with me.

**Comment by someone1** [comment]
@matthewrankin  - any chance you can create a v2 branch for us to point the changes to?

**Comment by matthewrankin** [comment]
@someone1 Done. I created a v2 branch.

**Comment by DerekDuchesne** [comment]
The PR is now pointing to the v2 branch and it includes moving the `baseURL` into a client option.

**Pull request merged**
